Form Ruby on Rails
pastorp3/Forms-RoR pull request #1
Opened 2020-09-08 21:38 UTC by pastorp3

The third project of Ruby on Rails, We create a model, controller, and views for User, Where you can create a new user and edit it and it will do the operation in the Data Base.

2020-09-08 23:53 UTC, kobiyoyo requested changes
## Hi Team    ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, everything works fine, but there are a few more things required. 
### General
- [ ] It’s better to delete **commented piece of codes**. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
- [ ] There should be a commented out html form ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_form1.png) [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_form2.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/forms))
- [ ] Also  a commented out `form_tag` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_form_tag2.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/forms))
- [ ] Check comments below

# \[OPTIONAL\]

* [ ] I encourage you to use a partial created for user form and reuse it in edit and new view
* [ ] validate the email format by using either a regular expression or a built-in URI method.### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2020-09-08 23:53 UTC, kobiyoyo commented on config/routes.rb
> +  resources :users, only: %i[new create edit]
- [ ]  Lets add `update` to the routes In config/routes.rb ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_route1.png) [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_route2.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/forms))

2020-09-08 23:53 UTC, kobiyoyo commented on app/controllers/users_controller.rb
> +    end
This should `render edit` if user was not saved ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_update.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/forms))

2020-09-08 23:53 UTC, kobiyoyo commented on app/controllers/users_controller.rb
> +      # flash.notice = "Some errors found try again!!!"
Remove this commented code

2020-09-08 23:53 UTC, kobiyoyo commented on app/controllers/users_controller.rb
> +    # @user = User.new(username: params[:username], email: params[:email], password: params[:password])
Remove this commented code

2020-09-08 23:53 UTC, kobiyoyo commented on app/views/users/edit.html.erb
> +<%= form_for @user, url:  "/users/#{@user.id}", method: :patch do |f| %>
this should be written this way `<%= form_for @user do |u|%>`

2020-09-08 23:53 UTC, kobiyoyo commented on app/views/users/edit.html.erb
> +  <%= f.text_field :email, placeholder: 'Your email'%>
`email_field` should be used here

2020-09-08 23:53 UTC, kobiyoyo commented on app/views/users/edit.html.erb
> +  <%= label_tag(:username) %>
This should be written like this `<%= u.label :username %>`

Note:implement changes to all the label tags

2020-09-09 03:36 UTC, Ispirett approved these changes
# Status Approved  :1st_place_medal: 
Great job folks have done well with all the changes made. :+1:

2020-09-09 13:00 UTC, merged